//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DanceCommunity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Journal
    {
        public int Id { get; set; }
        public int IdUser { get; set; }
        public int IdTraining { get; set; }
        public bool Visit { get; set; }
        public bool Protect { get; set; }
    
        public virtual Training Training { get; set; }
        public virtual User User { get; set; }
    }
}
