//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DanceCommunity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSchool
    {
        public int Id { get; set; }
        public int IdUser { get; set; }
        public int IdSchool { get; set; }
        public Nullable<bool> Type { get; set; }
    
        public virtual School School { get; set; }
        public virtual User User { get; set; }
    }
}
